echo -e "Interface\tRx\t\t\t\tTx\t"        
sh ifrateevery.sh wlan0                         
sh ifrateevery.sh br-lan                        
sh ifrateevery.sh eth0                         
sh ifrateevery.sh eth0.1                        
sh ifrateevery.sh eth0.2 
sh ifrateevery.sh gre0                      
sh ifrateevery.sh gretap0                      
sh ifrateevery.sh lo
sh ifrateevery.sh ifb0
sh ifrateevery.sh ifb1                           